import { Component, HostListener, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { TableSettings } from 'src/app/shared-module/Models/tableSettings.modal';


@Component({
  selector: 'app-alerts-list',
  templateUrl: './alerts-list.component.html',
  styleUrls: ['./alerts-list.component.scss']
})
export class AlertsListComponent implements OnInit {

  settings:TableSettings = {
    // tableBodyTdClass:'',
    tableClass:'min-w-full',
    tableHead:'bg-[#C0D7D6] font-semibold',
    tableHeadTrClass:'text-left',
    tableHeadTdClass:'tableHead pl-10',
    tableBodyTdClass: 'tableData pl-10',
    tableBodyTrClass:'',
    tableBody:'',
    enableActions:true,
    buttons:[
      {name:'view',class:'viewButton',func:(e)=>this.view(e)},
      // {name:'edit',class:'btn bg-green-400',func:this.edit.bind(this)},
      // {name:'delete',class:'btn bg-red-500',func:this.delete.bind(this)}
    ]
  }

  userservice:any
  gridData: any[]=[
    { id:'#20462', name:'Matt Dickerson1', date:'13/05/2022', time:'4:50 PM', counsellor:'Priya D',generatedby:'Counselor', alert: 'Green', 'report': '' },
    { id:'#20462', name:'Matt Dickerson2', date:'13/05/2022', time:'4:50 PM', counsellor:'Priya D',generatedby:'Counselor', alert: 'Green', 'report': '' },
    { id:'#20462', name:'Matt Dickerson3', date:'13/05/2022', time:'4:50 PM', counsellor:'Priya D',generatedby:'Counselor', alert: 'Green', 'report': '' }
  ];
  isEdit: boolean=false;


  colData = [
    { field: 'id', header: 'Employee ID' },
    { field: 'name', header: 'Name', class:'sort-icons' },
    { field: 'date', header: 'Date' },
    { field: 'time', header: 'Time' },
    { field: 'counsellor', header: 'Counsellor' },
    { field: 'generatedby', header: 'Generated by' },
    { field: 'alert', header: 'Alert', class:'alert1' },

  ]
  isDropDown?:boolean;

  // pagination variable
  POSTS: any;
  page: number = 1;
  count:number = 0;
  tableSize:number = 1;
  tableSizes: any = [5, 10, 15, 20]

  constructor( private router:Router ) { }

  ngOnInit(): void {
  }

  view(e:any):void{
    console.log("view called"+JSON.stringify(e));
    this.router.navigate(['/wellbeing-manager/user-risk-report'])
  }

  // edit(){
  //   console.log("edit called");
  // }

  // delete(){
  //   console.log("delete called");
  // }


  tableObj=[
    { id:'#20462', name:'Matt Dickerson1', date:'13/05/2022', time:'4:50 PM', counsellor:'Priya D',generatedby:'Counselor', alert: 'Green', 'report': '' },
    { id:'#20462', name:'Matt Dickerson2', date:'13/05/2022', time:'4:50 PM', counsellor:'Priya D',generatedby:'Counselor', alert: 'Green', 'report': '' },
    { id:'#20462', name:'Matt Dickerson3', date:'13/05/2022', time:'4:50 PM', counsellor:'Priya D',generatedby:'Counselor', alert: 'Green', 'report': '' },
  ]

  // tabbleDataRender(){
  //   // for(let i = 0; i<=this.tableObj.length; i++)
  //   // {
  //   //   this.gridData = this.gridData.push(this.tableObj[i])
  //   // }
  //   this.gridData = this.tableObj.concat()
  //   console.log(this.gridData);
  // }


  @HostListener('document:click', ['$event:'])
  clickoutside(event: any) {


    if (event && event.path && !event.target.className.includes("filterBtn")) {
      let found = false;
      let ar = [...event.path]
      for (let i = 0; i <= ar.length; i++) {
        let p = ar[i];
        found = p && p.className && p.className.includes("dropCheck");
        if (found)
          break;
      }
      if (found) {
        this.isDropDown = true;
      } else {
        this.isDropDown = false;
      }
    }

  }


}
